### ISSUE TITLE
请问如何下载npm环境啊,我是小白。

### ISSUE THREAD

**Issue by JavaFilter** [blacklisten/webpack-vue-demo#1]
感谢楼主大大

**Comment by CrazyChenzi** [comment]
@JavaFilter 官网下载node即可  [地址](https://nodejs.org/en/)

安装多个版本的[Node](https://www.blacklisten.cn/views/2020/%E5%A6%82%E4%BD%95%E5%AE%89%E8%A3%85%E5%A4%9A%E4%B8%AA%E7%89%88%E6%9C%AC%E7%9A%84node.html#window%E4%B8%8B%E4%BD%BF%E7%94%A8nvm)
